
# DataSource : Oracle
spring.datasource.driver-class-name=ENC(hlnVKQMcQCS19hbXS1kw+QKj70ZFcQD0MKjw77D+v5QXzZThFGRteAxhpqeKpJFydSRHtNXw9EA7OKFEqUHyZw==)
spring.datasource.url=ENC(33k79UtIuDudVDIMzsOvOgcHsmTDtBYLxi2E+NfSOtD/cHBO+ne+FBz6YRJp8J+D8HV3PSK2mSDhj+/QAfvrAROn7maJ/3LMmDYT/5ZNN1E=) 
spring.datasource.username=ENC(IV5SyzFqZcpJtNiOA1LRFW/KBxkATZoOMfP0nx9+TJFFeYOJYsQkOFK3Bg6ogPEx)
spring.datasource.password=ENC(kpvzJMV3QyJrHkrhbJ1s54+p6xHX1+HTcjCBvmd/D7btPr/5OkYNeM541LR57R2+)

#spring.autoconfigure.exclude=\
#org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
#org.springframework.boot.autoconfigure.data.jdbc.JdbcRepositoriesAutoConfiguration
# Mybatis : Default Setting, Override
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.jdbc-type-for-null=NULL
mybatis.type-aliases-package=com.pixcel.app
mybatis.mapper-locations=classpath:mapper/*/*.xml



# logging
#logging.level.com.pixcel.app=debug

# MultipartResolver Setting
# spring.servlet.multipart.file-size-threshold=0B
# spring.servlet.multipart.location=C:/temp
# spring.servlet.multipart.max-file-size=1MB
# spring.servlet.multipart.max-request-size=10MB

#JPA Basic Setting
#SQL, Display
spring.jpa.show-sql=true
#SQL, Easy Reading
spring.jpa.properties.hibernate.format_sql=true
#No Vender DDL
spring.jpa.generate-ddl=true
#JPA Database Setting
spring.jpa.database=oracle

#file.upload.path=D:/upload/

file.dir=C:/upload/repository/
file.path=/uploads

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
